"""Click-through links between rendered diagrams, read from a links file.

The links file (TOML) maps a source diagram to the elements in it that link
elsewhere::

    ["<source>"]                 # output file stem of the source diagram
    "<element name>" = "<target>"  # path relative to the source's directory

The source is the stem of the rendered file: the slug of a view's HTML file
for `archi render`, or the stem of a diagram generated by a project's own
scripts (for example a custom SVG). One file therefore decides about
click-through across both kinds of diagram, and can link between them.

Whether an element is clickable is an editorial choice, not a model fact, so
it lives in this sidecar and not in the model (ADR 0010).
"""
from __future__ import annotations

import os
import re
import tomllib
from pathlib import Path

from .model import ModelError

# targets that must not be prefixed: URLs with a scheme, absolute paths and
# in-page anchors
_NOT_RELATIVE = re.compile(r"^([a-z][a-z0-9+.-]*:|/|#)", re.IGNORECASE)


def load_links(path) -> dict:
    """Return {source: {element name: target}}; {} when no path is given."""
    if path is None:
        return {}
    path = Path(path)
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as exc:
        raise ModelError(f"Links-bestand {path} is geen geldige TOML: {exc}")
    links = {}
    for source, table in data.items():
        if not (isinstance(table, dict)
                and all(isinstance(v, str) for v in table.values())):
            raise ModelError(
                f"Links-bestand {path}: sectie '{source}' moet regels van de "
                "vorm \"elementnaam\" = \"pad\" bevatten")
        links[source] = dict(table)
    return links


def with_base(target: str, base: str) -> str:
    """Prefix a relative target with `base` (e.g. "../" when the diagram is
    embedded one directory deeper, as in the slide decks)."""
    if not base or _NOT_RELATIVE.match(target):
        return target
    return base + target


def links_for(links: dict, source: str, base: str = "") -> dict:
    """{element name: href} for one source diagram, prefixed with `base`."""
    return {name: with_base(target, base)
            for name, target in links.get(source, {}).items()}


def check_link_files(links: dict, views_root, html_dir, view_slugs) -> list:
    """Filesystem checks after rendering; returns warnings.

    A source must be a view (rendered to `html_dir`) or an existing file
    somewhere below `views_root` (e.g. a script-generated SVG); a target must
    exist relative to its source's directory. Targets that are URLs or
    absolute paths are not checked.
    """
    views_root, html_dir = Path(views_root), Path(html_dir)
    warnings = []
    for source, mapping in links.items():
        if source in view_slugs:
            source_dir = html_dir
        else:
            found = sorted(p for p in views_root.rglob(f"{source}.*")
                           if p.suffix in (".svg", ".html"))
            if not found:
                warnings.append(
                    f"Links: sectie '{source}' hoort bij geen view en bij geen "
                    f"bestand onder {views_root} (hernoemd of nog niet "
                    "gegenereerd?)")
                continue
            if len({p.parent for p in found}) > 1:
                # targets are relative to the source's directory, which is
                # ambiguous here; checking against an arbitrary one would
                # give misleading results
                candidates = ", ".join(str(p) for p in found)
                warnings.append(
                    f"Links: sectie '{source}' past bij meerdere bestanden "
                    f"({candidates}); doelen niet gecontroleerd")
                continue
            source_dir = found[0].parent
        for name, target in mapping.items():
            if _NOT_RELATIVE.match(target):
                continue
            # normalise ".." lexically first: POSIX resolves it through the
            # filesystem, so a not-yet-existing source dir would otherwise make
            # an existing target look missing (Windows already does this)
            if not Path(os.path.normpath(source_dir / target)).exists():
                warnings.append(
                    f"Links: '{source}' → '{name}' verwijst naar "
                    f"'{target}', dat niet bestaat")
    return warnings
